// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

public partial class Bolgeler
{
    [Key]
    [Column("TerritoryID")]
    [StringLength(20)]
    public string TerritoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string TerritoryTanimi { get; set; }

    [Column("BolgeID")]
    public int BolgeId { get; set; }

    [ForeignKey("BolgeId")]
    [InverseProperty("Bolgeler")]
    public virtual Bolge Bolge { get; set; }

    [ForeignKey("TerritoryId")]
    [InverseProperty("Territory")]
    public virtual ICollection<Personeller> Personel { get; } = new List<Personeller>();
}