// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

[Index("KategoriAdi", Name = "KategoriAdi")]
public partial class Kategoriler
{
    [Key]
    [Column("KategoriID")]
    public int KategoriId { get; set; }

    [Required]
    [StringLength(15)]
    public string KategoriAdi { get; set; }

    [Column(TypeName = "ntext")]
    public string Tanimi { get; set; }

    [Column(TypeName = "image")]
    public byte[] Resim { get; set; }

    [InverseProperty("Kategori")]
    public virtual ICollection<Urunler> Urunler { get; } = new List<Urunler>();
}