// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

[Index("Bolge", Name = "Bolge")]
[Index("PostaKodu", Name = "PostaKodu")]
[Index("Sehir", Name = "Sehir")]
[Index("SirketAdi", Name = "SirketAdi")]
public partial class Musteriler
{
    [Key]
    [Column("MusteriID")]
    [StringLength(5)]
    public string MusteriId { get; set; }

    [Required]
    [StringLength(40)]
    public string SirketAdi { get; set; }

    [StringLength(30)]
    public string MusteriAdi { get; set; }

    [StringLength(30)]
    public string MusteriUnvani { get; set; }

    [StringLength(60)]
    public string Adres { get; set; }

    [StringLength(15)]
    public string Sehir { get; set; }

    [StringLength(15)]
    public string Bolge { get; set; }

    [StringLength(10)]
    public string PostaKodu { get; set; }

    [StringLength(15)]
    public string Ulke { get; set; }

    [StringLength(24)]
    public string Telefon { get; set; }

    [StringLength(24)]
    public string Faks { get; set; }

    [InverseProperty("Musteri")]
    public virtual ICollection<Satislar> Satislar { get; } = new List<Satislar>();

    [ForeignKey("MusteriId")]
    [InverseProperty("Musteri")]
    public virtual ICollection<MusteriDemographics> MusteriType { get; } = new List<MusteriDemographics>();
}