// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

public partial class MusteriDemographics
{
    [Key]
    [Column("MusteriTypeID")]
    [StringLength(10)]
    public string MusteriTypeId { get; set; }

    [Column(TypeName = "ntext")]
    public string MusteriDesc { get; set; }

    [ForeignKey("MusteriTypeId")]
    [InverseProperty("MusteriType")]
    public virtual ICollection<Musteriler> Musteri { get; } = new List<Musteriler>();
}