// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

public partial class Nakliyeciler
{
    [Key]
    [Column("NakliyeciID")]
    public int NakliyeciId { get; set; }

    [Required]
    [StringLength(40)]
    public string SirketAdi { get; set; }

    [StringLength(24)]
    public string Telefon { get; set; }

    [InverseProperty("ShipViaNavigation")]
    public virtual ICollection<Satislar> Satislar { get; } = new List<Satislar>();
}