// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

[Index("PostaKodu", Name = "PostaKodu")]
[Index("SoyAdi", Name = "SoyAdi")]
public partial class Personeller
{
    [Key]
    [Column("PersonelID")]
    public int PersonelId { get; set; }

    [Required]
    [StringLength(20)]
    public string SoyAdi { get; set; }

    [Required]
    [StringLength(10)]
    public string Adi { get; set; }

    [StringLength(30)]
    public string Unvan { get; set; }

    [StringLength(25)]
    public string UnvanEki { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DogumTarihi { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? IseBaslamaTarihi { get; set; }

    [StringLength(60)]
    public string Adres { get; set; }

    [StringLength(15)]
    public string Sehir { get; set; }

    [StringLength(15)]
    public string Bolge { get; set; }

    [StringLength(10)]
    public string PostaKodu { get; set; }

    [StringLength(15)]
    public string Ulke { get; set; }

    [StringLength(24)]
    public string EvTelefonu { get; set; }

    [StringLength(4)]
    public string Extension { get; set; }

    [Column(TypeName = "image")]
    public byte[] Fotograf { get; set; }

    [Column(TypeName = "ntext")]
    public string Notlar { get; set; }

    public int? BagliCalistigiKisi { get; set; }

    [StringLength(255)]
    public string FotografPath { get; set; }

    [ForeignKey("BagliCalistigiKisi")]
    [InverseProperty("InverseBagliCalistigiKisiNavigation")]
    public virtual Personeller BagliCalistigiKisiNavigation { get; set; }

    [InverseProperty("BagliCalistigiKisiNavigation")]
    public virtual ICollection<Personeller> InverseBagliCalistigiKisiNavigation { get; } = new List<Personeller>();

    [InverseProperty("Personel")]
    public virtual ICollection<Satislar> Satislar { get; } = new List<Satislar>();

    [ForeignKey("PersonelId")]
    [InverseProperty("Personel")]
    public virtual ICollection<Bolgeler> Territory { get; } = new List<Bolgeler>();
}