// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

[Index("MusteriId", Name = "MusteriID")]
[Index("MusteriId", Name = "MusterilerSatislar")]
[Index("ShipVia", Name = "NakliyecilerSatislar")]
[Index("PersonelId", Name = "PersonelID")]
[Index("PersonelId", Name = "PersonellerSatislar")]
[Index("SatisTarihi", Name = "SatisTarihi")]
[Index("SevkPostaKodu", Name = "SevkPostaKodu")]
[Index("SevkTarihi", Name = "SevkTarihi")]
public partial class Satislar
{
    [Key]
    [Column("SatisID")]
    public int SatisId { get; set; }

    [Column("MusteriID")]
    [StringLength(5)]
    public string MusteriId { get; set; }

    [Column("PersonelID")]
    public int? PersonelId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SatisTarihi { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OdemeTarihi { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SevkTarihi { get; set; }

    public int? ShipVia { get; set; }

    [Column(TypeName = "money")]
    public decimal? NakliyeUcreti { get; set; }

    [StringLength(40)]
    public string SevkAdi { get; set; }

    [StringLength(60)]
    public string SevkAdresi { get; set; }

    [StringLength(15)]
    public string SevkSehri { get; set; }

    [StringLength(15)]
    public string SevkBolgesi { get; set; }

    [StringLength(10)]
    public string SevkPostaKodu { get; set; }

    [StringLength(15)]
    public string SevkUlkesi { get; set; }

    [ForeignKey("MusteriId")]
    [InverseProperty("Satislar")]
    public virtual Musteriler Musteri { get; set; }

    [ForeignKey("PersonelId")]
    [InverseProperty("Satislar")]
    public virtual Personeller Personel { get; set; }

    [InverseProperty("Satis")]
    public virtual ICollection<SatisDetaylari> SatisDetaylari { get; } = new List<SatisDetaylari>();

    [ForeignKey("ShipVia")]
    [InverseProperty("Satislar")]
    public virtual Nakliyeciler ShipViaNavigation { get; set; }
}