// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsNorthwind;

[Index("KategoriId", Name = "KategoriID")]
[Index("KategoriId", Name = "KategorilerUrunler")]
[Index("TedarikciId", Name = "TedarikciID")]
[Index("TedarikciId", Name = "TedarikcilerUrunler")]
[Index("UrunAdi", Name = "UrunAdi")]
public partial class Urunler
{
    [Key]
    [Column("UrunID")]
    public int UrunId { get; set; }

    [Required]
    [StringLength(40)]
    public string UrunAdi { get; set; }

    [Column("TedarikciID")]
    public int? TedarikciId { get; set; }

    [Column("KategoriID")]
    public int? KategoriId { get; set; }

    [StringLength(20)]
    public string BirimdekiMiktar { get; set; }

    [Column(TypeName = "money")]
    public decimal? BirimFiyati { get; set; }

    public short? HedefStokDuzeyi { get; set; }

    public short? YeniSatis { get; set; }

    public short? EnAzYenidenSatisMikatari { get; set; }

    public bool Sonlandi { get; set; }

    [ForeignKey("KategoriId")]
    [InverseProperty("Urunler")]
    public virtual Kategoriler Kategori { get; set; }

    [InverseProperty("Urun")]
    public virtual ICollection<SatisDetaylari> SatisDetaylari { get; } = new List<SatisDetaylari>();

    [ForeignKey("TedarikciId")]
    [InverseProperty("Urunler")]
    public virtual Tedarikciler Tedarikci { get; set; }
}