// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsMarket;

public partial class BrandsModels
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastModifiedOn { get; set; }

    [StringLength(50)]
    public string LastModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public int ParentId { get; set; }

    [Required]
    [StringLength(50)]
    public string Definition { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string ImageType { get; set; }

    public byte[] ImageBytes { get; set; }
}