// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AdoEntityDataModelTest.ModelsMarket;

public partial class MarketDBContext : DbContext
{
  public MarketDBContext(DbContextOptions<MarketDBContext> options)
      : base(options)
  {
  }

  public virtual DbSet<BrandsModels> BrandsModels { get; set; }

  public virtual DbSet<Categories> Categories { get; set; }

  public virtual DbSet<MarketUser> MarketUser { get; set; }

  public virtual DbSet<Musteriler> Musteriler { get; set; }

  public virtual DbSet<Test> Test { get; set; }

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    OnModelCreatingPartial(modelBuilder);
  }

  partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}