// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Market.Test.AdoEntityDataModel.Models;

public partial class Test
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Tanim { get; set; }

    [StringLength(500)]
    public string Aciklama { get; set; }
}